name: property_managment
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"



dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_lints: ^2.0.0
  flutter_svg: ^1.0.0 
  get: ^4.6.3
  get_storage: ^2.0.3
  dropdown_button2: ^1.0.0
  carousel_slider: ^4.1.1
  shared_preferences: ^2.0.15
  dio: ^4.0.6
  firebase_auth: ^4.1.1
  firebase_core: ^2.1.1
  json_annotation: ^4.4.0
  location: ^4.4.0
  geocoding: ^2.0.5
  provider: ^6.0.2
  geolocator: ^9.0.2
  js: ^0.6.2
  image_picker: ^0.8.6+1
  progress_indicators: ^1.0.0
  firebase_messaging: ^14.0.4
  flutter_local_notifications: ^12.0.3
  flutter_downloader: ^1.9.0
  animated_widgets: ^1.1.0
  animated_text_kit:   ^4.2.2
  google_fonts: ^3.0.1
  animations: ^2.0.7
  flutter_image_slideshow: ^0.1.4
  flutter_stripe: ^7.0.0
 




dev_dependencies:
  json_serializable: ^6.1.3
  build_runner: ^2.1.7 
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/font/

  # fonts:
  #   - family: Quantico
  #     fonts:
  #       - asset: assets/font/Quantico-Regular.ttf
  #       - asset: assets/font/Quantico-Italic.ttf
  #         weight: 300
  #       - asset: assets/font/Quantico-Regular.ttf
  #         weight: 400
  #       - asset: assets/font/Quantico-Bold.ttf
  #         weight: 600
  #       - asset: assets/font/Quantico-BoldItalic.ttf
  #         weight: 700
